### PR TITLE
summary for ben werdmuller article and tweet

### PR DESCRIPTION
**Pull request by andyzhu87**
submitting work for https://gitcoin.co/issue/FEMBusinessModelsRing/web3_revenue_primitives/7/2470

### CODE REVIEW

**Comment by Anish-Agnihotri** [comment]
Hey mate!

Looks like you're deleting a significant portion of the README when adding in the summary. I think that might be why the PR hasn't been merged.

Cheers,

Anish

**Comment by owocki** [comment]
yes please fix that, and also fix the merge conflicts!

**Comment by owocki** [comment]
closed via https://github.com/FEMBusinessModelsRing/web3_revenue_primitives/pull/23

**Comment by andyzhu87** [comment]
Hi @Anish-Agnihotri @owocki, sorry I've been out of town and did not realize I did that. Thanks for fixing it for me. Would love to contribute more to writing about biz models.

**Comment by Anish-Agnihotri** [comment]
Hey @andyzhu87, my apologies as well. 

Was doing another few additions as well, and decided to just do it at the same time, since it only took a minute.

Thanks for the great write up!

**Pull request closed without merging**
