### PR TITLE
Adding information regarding Gambling DAPPS.

### PR DESCRIPTION
**Pull request by Anish-Agnihotri**
Updating to include general summary + info regarding Ethercrash + Etheroll

Issue in reference: #44

### CODE REVIEW

**Comment by owocki** [comment]
adding some stuff about fomo3d would be cool!

**Comment by Anish-Agnihotri** [comment]
Oh right! Yes, I'll add stuff about that, funfair, and maybe xEther and Edgeless.

**Comment by Anish-Agnihotri** [comment]
Just threw in some information about Fomo3D and expanded existing content. LMK if it looks good for merge, or if you have other ideas I should add.

Left out xEther, Edgeless, and FunFair since they are not directly related to the ETH ecosystem and not completely representative of a replicable business model.

**Comment by owocki** [comment]
@Anish-Agnihotri thank you!

**Pull request merged**
